### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by dontlaugh** [Raku/cro-website#3]
This one: 

https://cro.raku.org/docs/intro/spa-with-cro

**Comment by librasteve** [comment]
I have:

- rebuilt the docker image and get the same missing link locally
- isolated the issue to content of cro-with-spa.md

**Comment by librasteve** [comment]
looks like removing an extra backtick patched the issue 

my guess is that the fourth stray backtick did something here:
https://github.com/Raku/cro-website/blob/d2d4fb466890966980dd7f8c3b091186c70ded18/lib/Routes.pm6#L73

**Comment by dontlaugh** [comment]
https://cro.raku.org/docs/intro/spa-with-cro

Thank you for the fix, @librasteve 

I don't have access to cro.services, so I can't fix that URL, sorry.
